"""Execute one (package, profiler) run.

The central mechanism is the *target contract* (README, "The target
contract"): the runner writes ``<RUN_DIR>/target.sh`` declaring the workload
as bash arrays -- ``TARGET_ARGV`` for prefix wrappers (time, py-spy) and
``TARGET_PYTHON_ARGV`` for interpreter replacements (viztracer, kernprof).
"""

from __future__ import annotations

import os
import re
import secrets
import shlex
import shutil
import signal
import subprocess
import sys
import threading
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Mapping, Optional

from discovery import Package, Profiler

_RUN_ID_SAFE = re.compile(r"[^A-Za-z0-9._-]+")

_LIB_DIR = Path(__file__).resolve().parent
#: The bash side of resolve()/execute(); see its header for the contract.
_HARNESS_SH = _LIB_DIR / "harness.sh"
#: The bash side of run_package_init().
_PACKAGE_INIT_SH = _LIB_DIR / "package_init.sh"


class RunError(Exception):
    """Raised for a run that cannot be set up (bad kind, missing entry, ...)."""


# The run currently in flight, so an interrupt can take its session down
# with it.  Runs are strictly sequential, so a single slot is enough.
_ACTIVE: "Optional[subprocess.Popen]" = None


def terminate_active() -> bool:
    """Kill the in-flight run's session, if any.  The workload runs in
    its own session, so a signal sent to the harness never reaches it."""
    proc = _ACTIVE
    if proc is None or proc.poll() is not None:
        return False
    _kill_session(proc)
    return True


@dataclass
class Target:
    kind: str
    python: Optional[str]
    argv: List[str]
    python_argv: Optional[List[str]]


@dataclass
class RunResult:
    package: str
    profiler: str
    status: str  # ok | failed | timeout | skipped
    run_id: Optional[str] = None
    run_dir: Optional[Path] = None
    exit_code: Optional[int] = None
    duration_s: float = 0.0
    reason: str = ""
    argv: List[str] = field(default_factory=list)
    command: List[str] = field(default_factory=list)
    started_at: str = ""
    finished_at: str = ""


# ---------------------------------------------------------------- run ids ---


def make_run_id(env: Mapping[str, str]) -> str:
    """Timestamped id, or a sanitized override from ``RUN_ID`` (CI build no.).

    An injected value becomes a directory name, so only ``[A-Za-z0-9._-]``
    survives -- it cannot escape the output tree.
    """
    override = (env.get("RUN_ID") or "").strip()
    if override:
        clean = _RUN_ID_SAFE.sub("-", override).strip("-.")[:128]
        if not clean:
            raise RunError(
                f"RUN_ID={override!r} does not contain any usable characters"
            )
        return clean
    return f"{time.strftime('%Y%m%d-%H%M%S')}-{secrets.token_hex(2)}"


# ------------------------------------------------------------ the target ---


def build_target(package: Package) -> Target:
    """Derive the target contract from the package's `.env` declarations.
    A ``package_command`` hook may later override it wholesale."""
    kind = package.kind
    entry = package.entry_point
    args = package.args
    workdir = Path(package.workdir)

    if kind not in ("python-module", "python-script", "exec"):
        raise RunError(
            f"package '{package.name}': unknown PACKAGE_KIND {kind!r} "
            "(expected python-module, python-script or exec)"
        )
    if not entry:
        raise RunError(
            f"package '{package.name}': PACKAGE_ENTRY is empty and package.sh "
            "defines no package_command"
        )

    if kind == "python-module":
        python = package.python
        python_argv = ["-m", entry, *args]
        return Target(kind, python, [python, *python_argv], python_argv)

    if kind == "python-script":
        python = package.python
        script = Path(entry)
        if not script.is_absolute():
            script = workdir / script
        python_argv = [str(script), *args]
        return Target(kind, python, [python, *python_argv], python_argv)

    # exec: no interpreter, so TARGET_PYTHON_ARGV stays unset.
    binary = Path(entry)
    if not binary.is_absolute() and (workdir / binary).exists():
        binary = workdir / binary
    return Target(kind, None, [str(binary), *args], None)


def render_target_sh(target: Target) -> str:
    """Serialize the target contract as a sourceable bash file."""
    lines = [
        "# Generated by the profiling harness -- do not edit.",
        "# Sourced by lib/common.sh consumers; see README.md 'The target contract'.",
        f"TARGET_KIND={shlex.quote(target.kind)}",
    ]
    if target.python:
        lines.append(f"TARGET_PYTHON={shlex.quote(target.python)}")
    else:
        lines.append("unset TARGET_PYTHON")

    lines.append(
        "TARGET_ARGV=(" + " ".join(shlex.quote(a) for a in target.argv) + ")"
    )
    if target.python_argv is None:
        # PACKAGE_KIND=exec has no interpreter to strip off.  Leaving the array
        # unset lets require_python_target fail with a readable message instead
        # of expanding to nothing and confusing the profiler's own CLI parser.
        lines.append("unset TARGET_PYTHON_ARGV")
    else:
        lines.append(
            "TARGET_PYTHON_ARGV=("
            + " ".join(shlex.quote(a) for a in target.python_argv)
            + ")"
        )
    return "\n".join(lines) + "\n"


# ------------------------------------------------------------- harnesses ---


def _hook_env(
    package: Package,
    profiler: Profiler,
    run_dir: Path,
    run_id: str,
    target_file: Path,
    argv_file: Path,
    command_file: Path,
) -> Dict[str, str]:
    """The environment every hook sees: the package's layered env plus the
    per-run variables."""
    out = dict(package.env)
    out.update(
        {
            "RUN_DIR": str(run_dir),
            "RUN_ID": run_id,
            "PACKAGE_NAME": package.name,
            "PROFILER_NAME": profiler.name,
            "PACKAGE_WORKDIR": str(package.workdir),
            # A hook's own directory, so profiler-specific helper scripts can
            # live beside the profiler that needs them instead of in lib/.
            "PACKAGE_DIR": str(package.entry.path),
            "PROFILER_DIR": str(profiler.entry.path),
            "PROFILING_PACKAGE_SH": str(package.entry.script_file),
            "PROFILING_PROFILER_SH": str(profiler.entry.script_file),
            "PROFILING_TARGET_FILE": str(target_file),
            "PROFILING_ARGV_FILE": str(argv_file),
            "PROFILING_COMMAND_FILE": str(command_file),
        }
    )
    return out


def _read_nul(path: Path) -> Optional[List[str]]:
    if not path.is_file():
        return None
    parts = [p.decode("utf-8", "replace") for p in path.read_bytes().split(b"\0") if p]
    return parts or None


def resolve(
    package: Package,
    profiler: Profiler,
    target: Target,
    scratch_dir: Path,
    run_dir: Path,
    run_id: str,
) -> "tuple[List[str], List[str]]":
    """Resolve (workload argv, profiler command) without running anything.

    Used by --dry-run.  ``run_dir`` is where the run *would* go, so the printed
    command names the real artifact paths; nothing is created there.
    """
    scratch_dir.mkdir(parents=True, exist_ok=True)
    target_file = scratch_dir / "target.sh"
    argv_file = scratch_dir / "argv"
    command_file = scratch_dir / "command"
    target_file.write_text(render_target_sh(target), "utf-8")

    hook_env = _hook_env(
        package, profiler, run_dir, run_id, target_file, argv_file, command_file
    )
    hook_env["PROFILING_RESOLVE_ONLY"] = "1"

    proc = subprocess.run(
        ["bash", str(_HARNESS_SH)],
        env=hook_env,
        cwd=_existing_dir(package.workdir, package.entry.path),
        stdin=subprocess.DEVNULL,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    if proc.returncode != 0:
        detail = proc.stderr.decode("utf-8", "replace").strip()
        raise RunError(
            f"could not resolve the command for {package.name}/{profiler.name}"
            + (f":\n{detail}" if detail else "")
        )

    return _read_nul(argv_file) or list(target.argv), _read_nul(command_file) or []


#: ``run_package_init`` returns this when package.sh defines no such hook.
#: Keep in sync with lib/package_init.sh.
NO_INIT_HOOK = 79


def run_package_init(package: Package) -> int:
    """Call ``package_init``; return its exit code (``NO_INIT_HOOK``: nothing
    to call -- a skip, not a failure).  No staleness caching of any kind:
    guarding repeat work is the hook's own job (README, "Package init")."""
    hook_env = dict(package.env)
    hook_env["PACKAGE_NAME"] = package.name
    hook_env["PACKAGE_DIR"] = str(package.entry.path)
    proc = subprocess.run(
        ["bash", str(_PACKAGE_INIT_SH), str(package.entry.script_file)],
        env=hook_env,
        cwd=_existing_dir(package.workdir, package.entry.path),
    )
    return proc.returncode


def reset_run_dir(run_dir: Path, output_root: Path) -> bool:
    """Clear an existing run directory (a pinned RUN_ID being re-run), so the
    previous attempt's artifacts cannot be listed in ``meta.json`` as this
    run's.  Returns True if anything was cleared; the containment check is
    belt and braces, since run_id is already a single sanitized component."""
    if not run_dir.is_dir():
        return False
    try:
        run_dir.resolve().relative_to(output_root.resolve())
    except ValueError:
        raise RunError(
            f"refusing to reset {run_dir}: it resolves outside {output_root}"
        )
    if not any(run_dir.iterdir()):
        return False

    for child in run_dir.iterdir():
        if child.is_dir() and not child.is_symlink():
            shutil.rmtree(child)
        else:
            child.unlink()
    return True


def execute(
    package: Package,
    profiler: Profiler,
    target: Target,
    run_dir: Path,
    run_id: str,
) -> RunResult:
    """Run the workload under the profiler, tee'ing output and enforcing
    PACKAGE_TIMEOUT by killing the whole session."""
    timeout = package.timeout
    run_dir.mkdir(parents=True, exist_ok=True)
    target_file = run_dir / "target.sh"
    target_file.write_text(render_target_sh(target), "utf-8")

    argv_file = run_dir / ".argv"
    command_file = run_dir / ".command"
    hook_env = _hook_env(
        package, profiler, run_dir, run_id, target_file, argv_file, command_file
    )

    started_at = _stamp()
    started = time.time()

    proc = subprocess.Popen(
        ["bash", str(_HARNESS_SH)],
        env=hook_env,
        cwd=_existing_dir(package.workdir, package.entry.path),
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        # Its own session, so a timeout can take the profiler *and* the
        # workload it spawned down together.
        start_new_session=True,
    )
    # Registered immediately: a signal arriving before this is set would skip
    # terminate_active and orphan the group we just created.
    global _ACTIVE
    _ACTIVE = proc

    stdout_log = run_dir / "stdout.log"
    stderr_log = run_dir / "stderr.log"
    teams = [
        threading.Thread(
            target=_tee, args=(proc.stdout, stdout_log, sys.stdout), daemon=True
        ),
        threading.Thread(
            target=_tee, args=(proc.stderr, stderr_log, sys.stderr), daemon=True
        ),
    ]
    for t in teams:
        t.start()

    timed_out = False
    try:
        try:
            exit_code = proc.wait(timeout=timeout)
        except subprocess.TimeoutExpired:
            timed_out = True
            _kill_session(proc)
            exit_code = proc.wait()
        except BaseException:
            # Ctrl-C, SIGTERM from a cancelled CI job, anything else: take the
            # session with us rather than orphaning the workload.
            _kill_session(proc)
            raise
    finally:
        _ACTIVE = None

    # Stamped at child exit, before waiting on the tee threads, so a slow
    # drain cannot inflate the workload's measured duration.
    duration = time.time() - started
    finished_at = _stamp()

    for t in teams:
        t.join(timeout=5)

    # What the harness actually resolved, which is what belongs in meta.json:
    # a package_command hook may have rewritten the workload, and the profiler
    # command is only known once its builder has run.
    argv = _read_nul(argv_file) or list(target.argv)
    command = _read_nul(command_file) or []
    argv_file.unlink(missing_ok=True)
    command_file.unlink(missing_ok=True)

    if timed_out:
        status, reason = "timeout", f"exceeded PACKAGE_TIMEOUT of {timeout:g}s"
    elif exit_code == 0:
        status, reason = "ok", ""
    else:
        status, reason = "failed", f"exited {exit_code}"

    return RunResult(
        package=package.name,
        profiler=profiler.name,
        status=status,
        run_id=run_id,
        run_dir=run_dir,
        exit_code=exit_code,
        duration_s=duration,
        reason=reason,
        argv=argv,
        command=command,
        started_at=started_at,
        finished_at=finished_at,
    )


def _tee(stream, path: Path, console) -> None:
    try:
        with path.open("wb") as fh:
            for chunk in iter(lambda: stream.readline(), b""):
                fh.write(chunk)
                fh.flush()
                try:
                    console.write(chunk.decode("utf-8", "replace"))
                    console.flush()
                except (ValueError, OSError):
                    pass
    finally:
        try:
            stream.close()
        except OSError:
            pass


def _live_session_pids(sid: int) -> List[int]:
    """Live (non-zombie) pids whose session id is ``sid``, via /proc.

    The harness child is started with ``start_new_session=True``, so its pid
    is the session id of everything it spawned, however deep.  Unlike a
    process group, a session cannot be left behind by bash's job control or
    by a tool calling setpgid()."""
    pids = []
    for entry in os.listdir("/proc"):
        if not entry.isdigit():
            continue
        try:
            with open(f"/proc/{entry}/stat", "rb") as fh:
                # The comm field may contain ') '; parse from the last ')'.
                fields = fh.read().rsplit(b")", 1)[-1].split()
        except OSError:
            continue  # the process raced away
        try:
            if int(fields[3]) == sid and fields[0] != b"Z":
                pids.append(int(entry))
        except (ValueError, IndexError):
            continue
    return pids


def _signal_pids(pids: List[int], sig: int) -> None:
    for pid in pids:
        try:
            os.kill(pid, sig)
        except (ProcessLookupError, PermissionError):
            pass


def _kill_session(
    proc: "subprocess.Popen",
    term_grace: float = 2.0,
    kill_grace: float = 5.0,
) -> None:
    """SIGTERM every live process in the child's session, then SIGKILL the
    survivors.

    By *session*, not by process group, and not just the direct child --
    both cheaper notions were observed to lie in this harness: bash can
    leave a profiler's command in a different process group, so a group kill
    orphaned GNU time and the workload it ran, and a zombie member keeps
    ``killpg(pgid, 0)`` reporting a group alive, stalling escalation for the
    whole grace period.  The child is its session's leader, and /proc says
    exactly who belongs to it.  The ~2 s window after SIGTERM is a courtesy
    for workloads that clean up on it.
    """
    sid = proc.pid
    doomed = _live_session_pids(sid)
    if not doomed and proc.poll() is None:
        doomed = [proc.pid]
    _signal_pids(doomed, signal.SIGTERM)

    try:
        proc.wait(timeout=term_grace)
    except subprocess.TimeoutExpired:
        pass

    deadline = time.monotonic() + kill_grace
    while True:
        survivors = _live_session_pids(sid)
        if not survivors:
            break
        # Re-sent every pass so anything forked between scans is caught too.
        _signal_pids(survivors, signal.SIGKILL)
        if time.monotonic() >= deadline:
            break
        time.sleep(0.05)
    _reap(proc)


def _reap(proc: "subprocess.Popen") -> None:
    try:
        proc.wait(timeout=5)
    except subprocess.TimeoutExpired:
        pass


def _existing_dir(*candidates) -> str:
    for candidate in candidates:
        if candidate and Path(candidate).is_dir():
            return str(candidate)
    return str(Path.cwd())


def _stamp() -> str:
    return time.strftime("%Y-%m-%dT%H:%M:%S%z", time.localtime())
